version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: autoui-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-123456}
      MYSQL_DATABASE: ${DB_NAME:-autoui_platform}
      MYSQL_USER: ${DB_USERNAME:-autoui}
      MYSQL_PASSWORD: ${DB_PASSWORD:-123456}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployments/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - autoui-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  autoui-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoui-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - SERVER_MODE=release
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=${DB_USERNAME:-autoui}
      - DB_PASSWORD=${DB_PASSWORD:-123456}
      - DB_NAME=${DB_NAME:-autoui_platform}
      - JWT_SECRET=${JWT_SECRET:-autoui-platform-secret-key-change-in-production}
      - CHROME_HEADLESS=true
      - CHROME_MAX_INSTANCES=10
    ports:
      - "8080:8080"
    volumes:
      - app_uploads:/app/uploads
      - app_screenshots:/app/screenshots
      - app_logs:/app/logs
    networks:
      - autoui-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: autoui-nginx
    restart: always
    depends_on:
      - autoui-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployments/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployments/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_uploads:/var/www/uploads:ro
      - app_screenshots:/var/www/screenshots:ro
    networks:
      - autoui-network

volumes:
  mysql_data:
    driver: local
  app_uploads:
    driver: local
  app_screenshots:
    driver: local
  app_logs:
    driver: local

networks:
  autoui-network:
    driver: bridge